version: '3'
services:
  redis:
    image: "redis:latest"
  etcd0:
    image: "quay.io/coreos/etcd:v2.3.8"
    command:
#      - /etcd
      - -name
      - etcd0
      - -advertise-client-urls
      - http://etcd0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
      - -initial-advertise-peer-urls
      - http://etcd0:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster
      - etcd0=http://etcd0:2380
      - -initial-cluster-state
      - new
  worker:
    image: "sound/worker"
    environment:
      REDIS_SERVICE_HOST: "redis"
      ETCD_CLIENT_SERVICE_HOST: "etcd0"
      JOB_TYPE: "green-alg"
  algoRunner:
    image: "sound/algorunner"
    environment:
      WORKER_SOCKET_HOST: "worker"
  worker2:
    image: "sound/worker"
    environment:
      REDIS_SERVICE_HOST: "redis"
      ETCD_CLIENT_SERVICE_HOST: "etcd0"
      JOB_TYPE: "green-alg"
  algoRunner2:
    image: "sound/algorunner"
    environment:
      WORKER_SOCKET_HOST: "worker2"
  api-server:
      image: "sound/api-server"
      ports:
        - 3000:3000
      environment:
        REDIS_SERVICE_HOST: "redis"
        ETCD_CLIENT_SERVICE_HOST: "etcd0"
  pipeline-driver:
      image: "sound/pipeline-driver"
      environment:
        REDIS_SERVICE_HOST: "redis"
        ETCD_CLIENT_SERVICE_HOST: "etcd0"
  pipeline-driver2:
        image: "sound/pipeline-driver"
        environment:
          REDIS_SERVICE_HOST: "redis"
          ETCD_CLIENT_SERVICE_HOST: "etcd0"


