apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-driver
  labels:
    app: pipeline-driver
    group: sound-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-driver
  template:
    metadata:
      labels:
        app: pipeline-driver
        group: sound-factory
    spec:
      containers:
      - name: pipeline-driver
        image: localhost:5000/sound/pipeline-driver:latest

