apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: worker-green
  labels:
    app: worker-green
    group: sound-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-green
  template:
    metadata:
      labels:
        app: worker-green
        group: sound-factory
    spec:
      containers:
      - name: worker
        image: localhost:5000/sound/worker
        env:
          - name: JOB_TYPE
            value: "green-alg"
      - name: algorunner
        image: localhost:5000/sound/algorunner

