apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
    group: hkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
        group: hkube
    spec:
      containers:
        - name: api-server
          image: 'registry.gitlab.com/greenapes/hkube/registry/api-server:latest'
          ports:
            - containerPort: 3000
          env:
            - name: BASE_URL_HOST
              value: 192.168.99.100
            - name: BASE_URL_PORT
              value: '30003'
      imagePullSecrets:
        - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  name: api-server
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: api-server
    group: hkube
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
  type: NodePort
