apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-driver
  labels:
    app: pipeline-driver
    group: hkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-driver
  template:
    metadata:
      labels:
        app: pipeline-driver
        group: hkube
    spec:
      containers:
        - name: pipeline-driver
          image: 'registry.gitlab.com/greenapes/hkube/registry/pipeline-driver:latest'
      imagePullSecrets:
        - name: regsecret
