%YAML 1.2
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webhook-stub-ui
  labels:
    app: webhook-stub-ui
    group: sound-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-stub-ui
  template:
    metadata:
      labels:
        app: webhook-stub-ui
        group: sound-factory
    spec:
      containers:
        - name: webhook-stub-ui
          image: 'registry.gitlab.com/greenapes/hkube/registry/webhook-stub-ui:latest'
          ports:
            - containerPort: 3002
            - containerPort: 3001
          env:
            - name: BASE_URL_HOST
              value: 192.168.99.100
            - name: BASE_URL_PORT
              value: '30001'
      imagePullSecrets:
        - name: regsecret
...
---
kind: Service
apiVersion: v1
metadata:
  name: webhook-stub-ui
  labels:
    app: webhook-stub-ui
    group: sound-factory
spec:
  selector:
    app: webhook-stub-ui
  ports:
    - name: server
      protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
    - name: socket
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
  type: NodePort
...
