apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: worker-black
  labels:
    app: worker-black
    group: sound-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-black
  template:
    metadata:
      labels:
        app: worker-black
        group: sound-factory
    spec:
      containers:
        - name: worker
          image: 'registry.gitlab.com/greenapes/hkube/registry/worker:latest'
          env:
            - name: JOB_TYPE
              value: black-alg
        - name: algorunner
          image: 'registry.gitlab.com/greenapes/hkube/registry/algo-package:latest'
      imagePullSecrets:
        - name: regsecret
